name = "Create Arcane Engineering"
author = "FortnitePro420Xx"
version = "Dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ad1a574ee6c24ce4aedcce1b15072ddea7187a6ca2e51ede4cfbea84adeadd44"

[versions]
forge = "40.2.9"
minecraft = "1.18.2"
