name = "Create Arcane Engineering"
author = "FortnitePro420Xx"
version = "Dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e4520f282a1db7dce1f0ce68afc8d81672d07f4188801f3b471e8cf946c02fcb"

[versions]
forge = "40.2.9"
minecraft = "1.18.2"
