name = "Create Arcane Engineering"
author = "FortnitePro420Xx"
version = "Dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8f2ec730cb271411ef052f3d71da93f324ce32b13c2e07d370f06746f7ada10d"

[versions]
forge = "40.2.9"
minecraft = "1.18.2"
